### ISSUE TITLE
SQLModel suggestion

### ISSUE THREAD

**Issue by epogrebnyak** [vancanhuit/url-shortener#6]
Great project example in your repo! Have you considered https://sqlmodel.tiangolo.com/ as ORM? 
Should play nicely with FastAPI.

**Comment by vancanhuit** [comment]
Thanks for your suggestion but I prefer to learn and use plain SQLAlchemy.

**Comment by epogrebnyak** [comment]
> Thanks for your suggestion but I prefer to learn and use plain SQLAlchemy.

Makes sense! Mind if I fork your original project and make a version with SQLModel? 

I have question about the code for shortener - are first 7 digits of the hash guaranteed to be unique? Is there some guidance to use it?

**Comment by vancanhuit** [comment]
Feel free to fork it and do what you want to do. The 7 chars for short link is just my arbitrary decision.

**Comment by epogrebnyak** [comment]
Keeping this for a reference on shortening: https://github.com/puyuan/py-nanoid

**Comment by vancanhuit** [comment]
Thanks for the reference.
